disabled_rules:
- trailing_whitespace
- nesting

excluded:
- Pods/
- Podfile
- Podfile.lock
- AppDelegare.swift
- /Users/kando/Desktop/nri/XCTest_swift/Carthage/Checkouts/Alamofire/

line_length: 300
